### ISSUE TITLE
Home Page Themes Broken

### ISSUE THREAD

**Issue by Lavender-Daydream** [doqmeat/doqmeat.com#55]
Just reloaded your website tonight and it looks like the home page themes broke. I'm also using firefox on pc.

![](https://github.com/user-attachments/assets/4a472ade-ff8e-4c1c-abde-eef11ab9cee4)

**Comment by doqmeat** [comment]
i updated the javascript file likeee an hour ago so it's probably that the cache needs to be cleaned. because i checked and it's working properly on my end and also on chrome which i barely use. you could do a CTRL + F5 or on firefox click the 3 lines at the top right  > history > clear recent history... > check "temporary cached files" > clear and that should do the trick

**Comment by Lavender-Daydream** [comment]
That worked! Ty!
